name: Matplotlib Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.1 # Choose the Python version you want to use

    - name: Install dependencies
      run: |
        pip install matplotlib

    - name: Run Matplotlib Code
      run: |
        python ex.py # Replace with the name of your Python script that contains the Matplotlib code
