name: Matplotlib Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install numpy matplotlib

    - name: Run Matplotlib Code
      run: |
        python ex.py

    - name: Commit and Push Changes
      run: |
        git config --global user.email "imxasik@gmail.com"
        git config --global user.name "imxasik"
        git add test.png
        git commit -m "Matplotlib plot"
        git push https://$GH_PAT@github.com/username/repository.git HEAD:branch-name
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
