name: Matplotlib Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install numpy matplotlib

    - name: Run Matplotlib Code
      run: |
        python ex.py

    - name: List Artifacts
      run: |
        echo "List of artifacts:"
        ls -la $GITHUB_WORKSPACE/.github/artifacts/

    - name: Upload Plot as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_plot
        path: test.png
