name: Run 6 Hours

on:
  schedule:
    - cron: '15 */6 * * *'  # Schedule to run every 6 hours starting from 0:30 UTC

jobs:
  generate-plot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install matplotlib pandas ftputil lxml

      - name: Run Python Script
        run: python Dhaka_temp.py

      - name: Run Wind Python Script
        run: python Dhaka_wind.py

      - name: Run Wind Python Script
        run: python Jashore_temp.py

      - name: Run Wind Python Script
        run: python Jashore_wind.py
