name: Run Every 3Hrs

on:
  schedule:
    - cron: '45 0,1,6,7,12,13,18,19 * * *'  # Runs at 01:30, 07:30, 13:30, and 19:30 UTC

jobs:
  generate-plot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade Pip
        run: pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run TC Scripts
        run: |
          set -e  # Fail fast on errors
          python tc_io.py
          python tc_wp.py
          python tc_al.py
          python tc_ep.py
          python tc_cp.py
          python tc_sh.py
