name: Web Manual Runs

on:
  workflow_dispatch:  # This allows running the workflow manually from GitHub

jobs:
  visit-website:
    runs-on: ubuntu-latest

    steps:
      - name: Visit Website
        run: curl -k -I https://xpwx.rf.gd/radar/auto.php
