name: Manual Runs

on:
  workflow_dispatch:  # This allows running the workflow manually from GitHub

jobs:
  generate-plot:
    runs-on: ubuntu-latest

    steps:
      - name: Visit Website
        run: curl -I https://xpwx.rf.gd/radar/auto.php  # Replace "https://example.com" with the URL of the website you want to visit
